hydra:
  run:
    dir: outputs/compare_cf/${output_path}

defaults:
  - encoder: hf_bert # defines encoder initialization parameters
  - datasets: retriever_default # contains a list of all possible sources of queries for evaluation. Specific set is selected by qa_dataset parameter
  - ctx_sources: default_sources # contains a list of all possible passage sources. Specific passages sources selected by ctx_datatsets parameter
  - override hydra/job_logging: def

# the name of the queries dataset from the 'datasets' config group
qa_dataset:

# a list of names of the passages datasets from the 'ctx_sources' config group
ctx_datasets:

#Glob paths to encoded passages (from generate_dense_embeddings tool)
encoded_ctx_files: []

output_path: 
out_file: scores.json
# "regex" or "string"
match: string
n_docs: 100
validation_workers: 16

# Batch size to generate query embeddings
batch_size: 256

# Whether to lower case the input text. Set True for uncased models, False for the cased ones.
do_lower_case: True

# path to the FAISS index location - it is only needed if you want to serialize faiss index to files or read from them
# (instead of using encoded_ctx_files)
# it should point to either directory or a common index files prefix name
# if there is no index at the specific location, the index will be created from encoded_ctx_files
index_path:

# A trained bi-encoder checkpoint file to initialize the model
model_file:


# RPC settings
rpc_retriever_cfg_file:
rpc_index_id:
use_l2_conversion: False
use_rpc_meta: False
rpc_meta_compressed: False

indexer: flat

# tokens which won't be slit by tokenizer
special_tokens:

# TODO: move to a conf group
# local_rank for distributed training on gpus
local_rank: -1
global_loss_buf_sz: 150000
device:
distributed_world_size:
distributed_port:
no_cuda: False
n_gpu:
fp16: False

# For fp16: Apex AMP optimization level selected in ['O0', 'O1', 'O2', and 'O3']."
#        "See details at https://nvidia.github.io/apex/amp.html
fp16_opt_level: O1

gold_info:
input_file: 
output_remove_percentage: False
use_title: True

num_ckpt: 0